baseURL = 'https://blog.20250331.xyz/'
languageCode = 'zh-cn'
title = "Spark's Blog"
theme = 'FixIt'

[params]
title = "Spark's Blog"
description = "A Blog of a student from China"

ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowWordCount = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
ShowCodeCopyButtons = true

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false


[params.author]
name = "Spark"
mail = "Spark-CN@outlook.com"
avatar = "https://s2.loli.net/2025/11/15/z452tUPHnam1bCX.jpg"

[params.home]
  [params.home.profile]
  enable = true
  social = true
  title = 'Hi! This blog belongs a student from China'
# subtitle = 'You can find me throught following platforms'

[params.footer]
enable = true
copyright = true
author = true
since = "2025"
license = "CC BY-NC-SA 4.0"
[params.footer.powered]
  enable = true
  hugoLogo = true
  themeLogo = true

[params.social]
email = "Spark-CN@outlook.com"
Mastodon = "@Spark2025"
GitHub = "PILIHU2022"

[params.tagcloud]
enable = true
min = 14
max = 32
peakCount = 10
orderby = "name"

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1
[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 2
[[menus.main]]
name = "Dairy"
pageRef = "/dairy"
weight = 3
[[menus.main]]
name = 'About Me'
parent = 'About'
pageRef = "/about"
weight = 8
# [[menus.main]]
# name = "Contact Me"
# pageRef = "/contact"
# weight = 8
[[menus.main]]
parent = 'About'
name = 'Friends'
pageRef = "/friends"
weight = 9

[taxonomies]
tag = 'tags'
category = "categories"
collection = "collections"

paginationSize = 100
listSummaries = true
