baseURL = 'https://blog.20250331.xyz/'
languageCode = 'zh-cn'
title = "Spark's Blog"
theme = 'FixIt'

[params]
title = "Spark's Blog"
description = "A Blog of a student from China"
dateFormat = ""

ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowWordCount = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
ShowCodeCopyButtons = true

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false
externalIcon = true

[params.author]
name = "Spark"
email = "Spark-CN@outlook.com"
link = "https://blog.20250331.xyz/"
avatar = "https://sm.ms/image/z452tUPHnam1bCX"

[params.homeInfoParams]
Title = 'Hi! This blog belongs a student from China'
# Content = 'You can find me throught following platforms'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/PILIHU2022'
[[params.socialIcons]]
name = 'gitlab'
url = 'https://gitlab.com/PILIHU'
[[params.socialIcons]]
name = 'email'
url = 'mailto:Spark-CN@outlook.com'

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1
[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 2

[[menus.main]]
name = 'About'
pageRef = "/about"
weight = 10
[[menus.main]]
parent = "About"
name = 'Contact Me'
pageRef = "/about/contact"
[[menus.main]]
parent = "About"
name = 'Friends'
pageRef = "/about/friends"

[taxonomies]
tag = 'tags'
category = "categories"

paginationSize = 100
listSummaries = true
# listDateFormat = '2025 Jul 28'
